//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Heizung.cpp
//  @ Date : 17.05.2021
//  @ Author : 
//
//


#include "Heizung.h"

void Heizung::setTemp(int heizung_bez, int sollwert) {
}

