//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Heizung.h
//  @ Date : 17.05.2021
//  @ Author : 
//
//


#if !defined(_HEIZUNG_H)
#define _HEIZUNG_H


class Heizung {
public:
	float sollwert;
	string heizung_bez;
	void setTemp(int heizung_bez, int sollwert);
};

#endif  //_HEIZUNG_H
