//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Raum.h
//  @ Date : 17.05.2021
//  @ Author : 
//
//


#if !defined(_RAUM_H)
#define _RAUM_H


class Raum {
public:
	string bezeichner;
	float avg_temp;
};

#endif  //_RAUM_H
