//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Temperatursensor.cpp
//  @ Date : 17.05.2021
//  @ Author : 
//
//


#include "Temperatursensor.h"

float Temperatursensor::getTemp(int temp_bez) {
}

