//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Temperatursensor.h
//  @ Date : 17.05.2021
//  @ Author : 
//
//


#if !defined(_TEMPERATURSENSOR_H)
#define _TEMPERATURSENSOR_H


class Temperatursensor {
public:
	string temp_bez;
	float temp;
	float getTemp(int temp_bez);
};

#endif  //_TEMPERATURSENSOR_H
