//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Window.h
//  @ Date : 17.05.2021
//  @ Author : 
//
//


#include <string>

#if !defined(_WINDOW_H)
#define _WINDOW_H


class Window {
public:
	std::string window_bez;
	int zustand;
	void setWindow(int window_bez, int zustand);
	int getWindow(int window_bez);
};

#endif  //_WINDOW_H
