//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Window.cpp
//  @ Date : 17.05.2021
//  @ Author : 
//
//


#include "Window.h"

void Window::setWindow(int window_bez, int zustand) {
	//IMPLEMENT HERE!!!!!!!!!!!
	return;
}

int Window::getWindow(int window_bez) {
	//IMPLEMENT HERE!!!!!!!!!!!
	return -1;
}

