//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Zugang.h
//  @ Date : 17.05.2021
//  @ Author : 
//
//


#if !defined(_ZUGANG_H)
#define _ZUGANG_H


class Zugang {
public:
	bool zustand;
	string zugang_bez;
	bool lock(string zugang_bez);
	bool unlock(string zugang_bez);
	bool getZustand(string zugang_bez);
};

#endif  //_ZUGANG_H
