//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Zugang.cpp
//  @ Date : 17.05.2021
//  @ Author : 
//
//


#include "Zugang.h"
#include <string>

using namespace std;

bool Zugang::lock(string zugang_bez) {
	
}

bool Zugang::unlock(string zugang_bez) {
}

bool Zugang::getZustand(string zugang_bez) {
}

